/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Button: typeof import('@/components/ui/layout').Button
  const Input: typeof import('@/components/ui/layout').Input
  const Label: typeof import('@/components/ui/layout').Label
  const Link: typeof import('react-router-dom').Link
  const LoginForm: typeof import('@/components/ui/layout').LoginForm
  const NavLink: typeof import('react-router-dom').NavLink
  const Navigate: typeof import('react-router-dom').Navigate
  const Navigation-menu: typeof import('@/components/ui/layout')['Navigation-menu']
  const NavigationMenu: typeof import('@/components/ui/layout').NavigationMenu
  const NavigationMenuContent: typeof import('@/components/ui/layout').NavigationMenuContent
  const NavigationMenuIndicator: typeof import('@/components/ui/layout').NavigationMenuIndicator
  const NavigationMenuItem: typeof import('@/components/ui/layout').NavigationMenuItem
  const NavigationMenuLink: typeof import('@/components/ui/layout').NavigationMenuLink
  const NavigationMenuList: typeof import('@/components/ui/layout').NavigationMenuList
  const NavigationMenuTrigger: typeof import('@/components/ui/layout').NavigationMenuTrigger
  const NavigationMenuViewport: typeof import('@/components/ui/layout').NavigationMenuViewport
  const Outlet: typeof import('react-router-dom').Outlet
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const useParams: typeof import('react-router-dom').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
